### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#10]
Our philosophy for themes is based on a continuity between content and reading app. This means that any theme applied to the content will also impact the playground itself in terms of:

- background color
- text color
- primary color
- and secondary color

We'll need to decide if that's the case of fonts too. This can be a little more risky, but in the case of specialized fonts, it could make a lot of sense as well.

Throughout this Epic, we will:

- [x] Set-up support for themes through the use of CSS custom properties
- [x] Implement a default that follows system settings for dark/light modes
- [x] Set up additional themes: light, dark, sepia, paper and high contrast themes
- [x] Add support for theme-switching in user settings
- [x] Global setting per publication type (reflow vs EPUB, audiobook will be a separate setting in the future)

**Comment by JayPanoz** [comment]
Following this morning’s discussion, after checking [Material Design 3 for inspiration](https://m3.material.io/styles/color/roles), themes should have the following properties in terms of customisation: 

- `background`
- `text`
- `link` and `visited`
- `subdue`
- `disable`
- `hover` + `onHover`
- `select` + `onSelect` (also applied to `::selection` in contents) 
- `focus`
- `dropShadow`/`elevate`
- `opacity`/`immerse` (immersive mode)
