### ISSUE TITLE
Support for actions as icons, including support for action visibility

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#13]
With this task, we'll cover the most basic support for actions when displayed as icons:

- [x] displaying an icon
- [x] label when hovering over the icon
- [x] visibility for icons (always visible, partially visible)

**Comment by JayPanoz** [comment]
Question: we already have an hover set for the top and bottom bars so how does this behaviour should evolve with the requirement of hovering over the icon?

Answer: implementation is good as-is, with top and bottom bars sync’d and actions as part of it.
