### ISSUE TITLE
Overflow button and menu, including support for collapsibility

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#14]
For the overflow menu, we'll take inspiration from two affordances available on mobile platforms:

- https://m3.material.io/components/menus/overview
- https://developer.apple.com/design/human-interface-guidelines/menus

Given the importance of desktop for Web reading, we'll use the following layout approach for items in the menu:

- icon on the left
- text of the action next to it
- optional keyboard shortcut on the right

The overflow button itself is displayed as an icon and remains visible in immersive mode (but should it remain visible in full screen mode?).

While working on this task, we'll also need to support collapsibility for actions displayed as icons.

We'll cover things in the following order:

- [x] add an overflow icon to actions
- [x] implement support for the menu
- [x] and implement support for collapsibility

**Comment by JayPanoz** [comment]
At the moment collapsibility is implemented as a `boolean` and is relying on the breakpoint already used for the optimal line-length, but it’s been discussed this is not the best approach. The concept of collapsibility will therefore be fine-tuned in the upcoming days.
