### ISSUE TITLE
Define windows size classes

### ISSUE THREAD

**Issue by JayPanoz** [edrlab/thorium-web#28]
At the moment the playground is using a single breakpoint (default is `1024`) to handle line-length, collapsibility (although that is going to change, see #14) as a simplistic way to handle “responsive”. 

However, we’ve discussed having different components for mobile (e.g. sheets) so there’s the overarching issue of defining what mobile is, especially as the lines can be blurry nowadays.

Although generally not recommended, it’s one of these challenges for which it’s kinda difficult to ignore user-agent sniffing, especially as [solutions that provide views are already available for React](https://www.npmjs.com/package/react-device-detect) and our use case is a lot more complex than checking for a screen size… 

But I’m guessing we will perhaps have to refine that even further with [media queries and device features/capabilities](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries).

Of course the biggest challenge is trying to design a good abstraction or something simple enough that we don’t have to keep track of new hardware in order to modify things specifically for it. 

Will share some thoughts later but in the meantime, feedbacks and thoughts obviously welcome as it’s not an uncommon issue and some people will have already tackled that.

**Comment by JayPanoz** [comment]
Note that when switching to the dynamic breakpoint based on the optimal line-length, we lost the logic for FXL (primarily overlaid versus docked arrows). 

@HadrienGardeur We may want to keep that in mind as we’ve not discussed if we want to keep things consistent across EPUB renditions or a specific UI.

**Comment by HadrienGardeur** [comment]
Right, we might need to keep the breakpoint (or an equivalent) for "visual publications" such as FXL, comics and/or PDF.

We could look at what Google has done for inspiration: https://m3.material.io/foundations/layout/applying-layout/window-size-classes
