### ISSUE TITLE
Failed loading manifest https://playground.readium.org/books/moby-dick/manifest.json

### ISSUE THREAD

**Issue by xibsked** [edrlab/thorium-web#3]
Looks like playground is not working.

![image](https://github.com/user-attachments/assets/5a5a7df4-8d33-4767-bee2-f23f8bb0f469)

**Comment by HadrienGardeur** [comment]
The playground is very much a WIP and it's missing a homepage with a publication list in its current state.

Here's what you were probably looking for: https://playground.readium.org/?book=https://publication-server.readium.org/bW9ieS1kaWNrLmVwdWI
