### ISSUE TITLE
Support for scrolled content and core affordances

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#8]
For now, support for scrolled content will be strictly limited to reflowable EPUB. This will hopefully be extended at a later point to FXL and comics/manga as well (and webtoons of course).

To implement this mode, we'll need to:

- [x] force a centered single column of text
- [x] hide progression for now (x of y)
- [x] hide progression affordance (arrows) used in paginated mode
- [x] add forward/backward buttons at the top and bottom of each resource
- [x] map keyboard navigation to scrolled (up, down, space to move to a screen worth of content)

Rules for displaying these next/previous buttons should be covered in reading system preferences where each implement could decide to show:

- [x] both buttons at the top and bottom
- [x] both buttons at the bottom
- [x] only backward at the top and forward at the bottom
- [x] only forward at the bottom

**Comment by HadrienGardeur** [comment]
We should explore setting a longer optimal line length (75 characters) when reading in scrolling mode since multi-column layouts won't be available.

For the forward/backward affordances, we'll take inspiration from Gitbook, as illustrated by this example: https://support.audacityteam.org/

These buttons are included in the content area (iframe) rather than displayed next to it.

**Single button**

<details>
  <summary>Example of a full-width button</summary>

![Forward button](https://github.com/user-attachments/assets/ff92b724-ea60-4fe3-ab64-db83a6bee3f4)

</details>

- If a single action is displayed at the top/bottom, we'll display a full-width button indicating the nature of the affordance (Next/Previous).
- Text-alignment and the arrow direction will also be used to convey the nature of this action.

**Dual buttons**

<details>
  <summary>Example of two half-width button</summary>

![Two buttons](https://github.com/user-attachments/assets/5d68866c-9029-45ef-991c-194458b1f552)

</details>

- When two buttons are displayed each of them take half of the column width

**Comment by JayPanoz** [comment]
> These buttons are included in the content area (iframe) rather than displayed next to it.

Just to confirm, that means injected into the iframe's document, right? 

It's feasible, I actually started the implementation testing that w/o any styling, but was worried about possible side effects and seeing other implementations use an external component to achieve this feature.

In any case the (very crude at the moment) component is not lost and I can switch back to injecting into the iframe's document. I think it would be a good idea to document concerns, caveats and issues if we come across any though.

**Comment by HadrienGardeur** [comment]
To get the kind of "native to the Web" feeling that we're looking for, I feel that this is somehow necessary.

**Comment by HadrienGardeur** [comment]
Based on the current branch deployed on CF (October 29 2024):

- I can still see a dedicated bottom space below the content area while scrolling, which should be hidden instead
- I think that there's no need to display a label underneath "Previous/Next" for now, we'll improve this later on using the ToC in another milestone
- the buttons are not of the same size right now, probably due to the label, which shouldn't impact the size of the button IMO (we'll truncate the label using CSS and "…" instead)
- let's avoid using uppercase text in the UI if we can ("Previous/Next")
- the border of the buttons should be grey instead of black (once again, I think that Gitbook took the right approach with that)

I don't think that we've talked about the defaults yet, but I see that you went with a single back button on top and both buttons at the bottom.
This is good for testing the look/feel of both full sized and half sized button, but I'm tempted to only use buttons at the bottom as our defaults.

One thing that we've also forgot to discuss is the scrolling state of adjacent resources when using next/previous.
I'm mostly targeting a Web-like behavior with this affordance, which means that even when we go back to the previous ressource, I think that we should start at the top. But this is typically something that should be covered by Reading System Preferences, where some implementers could target the bottom of the ressource instead.

Still, this is something to keep in mind when interacting with the navigator, because it might keep the previous scroll position. This means that we need the ability to reset this position to go to the top/bottom.

**Comment by JayPanoz** [comment]
Thanks for listing all these details. 

I had planned getting back to it indeed so it will help quite a lot. Navigator is higher priority right now. The TL;DR is that it will help manage the lifecycle of contents more reliably since scroll affordances are currently suffering from edge–cases due to this, and I need the refactor ASAP to fix this issue then focus on the finer details. 🙏
